
sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - libopencv-dev
      - libcv-dev
      - libboost-all-dev
      - libpq-dev
      - postgresql-server-dev-9.3

before_install:
  - sudo apt-get install build-essential
  - wget http://www.cmake.org/files/v3.7/cmake-3.7.2.tar.gz
  - tar xf cmake-3.7.2.tar.gz
  - cd cmake-3.7.2
  - ./configure
  - make && make install && cd ..
  - cmake --version
  - psql --version

before_script:
  - git clone https://github.com/celian-garcia/fly.git && cd fly
  - mkdir build && cd build
  - cmake .. && make
  - cd ../..
  - mkdir build && cd build
  - cmake -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgres/9.3/server ..

script: make