
sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - libopencv-dev
      - libcv-dev
      - libboost-all-dev
      - libpq-dev
      - postgresql-server-dev-all

before_install:
  - sudo apt-get install build-essential
  - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz
  - tar xf cmake-3.7.2-Linux-x86_64.tar.gz
  - cd cmake-3.7.2-Linux-x86_64
  - ./configure
  - make && cd ..
  - cmake --version
  - psql --version


before_script:
  - git clone https://github.com/celian-garcia/fly.git && cd fly
  - mkdir build && cd build
  - cmake .. && make
  - cd ../..
  - mkdir build && cd build
  - cmake ..

script: make