
sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-6
      - libopencv-dev
      - libcv-dev
      - libboost-all-dev
      - libpq-dev
      - postgresql-server-dev-9.3

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - wget http://www.cmake.org/files/v3.7/cmake-3.7.2.tar.gz
  - tar xf cmake-3.7.2.tar.gz
  - cd cmake-3.7.2
  - ./configure
  - make && sudo make install && cd ..
  - cmake --version
  - psql --version

before_script:
  - git clone https://github.com/celian-garcia/fly.git && cd fly
  - mkdir build && cd build
  - cmake .. && make
  - cd ../..
  - mkdir build && cd build
  - cmake -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgres/9.3/server  -DFly_DIR="/home/travis/build/celian-garcia/firefly/fly" ..

script: make