
sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:george-edison55/cmake-3.5'

    packages:
      - cmake
      - cmake-data
      - libopencv-dev
      - libcv-dev
      - libboost-all-dev
      - libpq-dev
      - postgresql-server-dev-all

before_install:
  - psql --version
  - cmake --version


before_script:
  - git clone https://github.com/celian-garcia/fly.git && cd fly
  - mkdir build && cd build
  - cmake .. && make
  - cd ../..
  - mkdir build && cd build
  - cmake ..

script: make