
sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:george-edison55/cmake-3.x'

    packages:
      - cmake
      - cmake-data
      - libopencv-dev
      - libcv-dev
      - libboost-all-dev
      - libpq-dev
      - postgresql-server-dev-9.3

before_install:
  - cmake --version
  - psql --version

before_script:
  - git clone https://github.com/celian-garcia/fly.git && cd fly
  - mkdir build && cd build
  - cmake .. && make
  - cd ../..
  - mkdir build && cd build
  - cmake -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgres/9.3/server ..

script: make