version: '3'
services:
  server:
    build: .
    ports:
      - "9080:9080"
    volumes:
      - "./config/dev-docker.toml:/etc/firefly/config.toml"
    command: /usr/bin/FIREFLY_LAUNCHER /etc/firefly/config.toml
  database:
    image: "celiangarcia/firefly-database:0.2.0"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=firefly_hive
    ports:
      - "5400:5432"