version: 2
jobs:
  build:
    machine: true
#    docker:
#      - image: circleci/ubuntu-server:latest
    steps:
      - checkout
      - run: 
          name: Log in to docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: 
          name: Build image from Dockerfile
          command: docker build -t $DOCKER_USER/firefly-api:0.1 .
      - run:
          name: Push image to docker hub
          command: docker push $DOCKER_USER/firefly-api:0.1
#      - run:
#          name: Install Docker Compose
#          command: |
#            set -x
#            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
#            chmod +x /usr/local/bin/docker-compose
     
#      - setup_remote_docker
#      - run:
#          name: Start container and verify it's working
#          command: |
#            set -x
#            docker-compose up -d
  analysis:
    docker:
      - image: celiangarcia/firefly-api-base-sonar:0.1
    steps:
      - checkout
      - run:
          name: Build app using sonar's build wrapper
          command: |
            mkdir build
            cd build
            cmake -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql ..
            build-wrapper --out-dir wrapper-output  make -j12
      - run:
          name: Run sonar with maven
          command: mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=celian-garcia-github -Dsonar.login=$SONAR_LOGIN -Dsonar.cfamily.build-wrapper-output=./build/wrapper-output -Dsonar.sourceEncoding=UTF-8 -Dsonar.cpp.std=c++17
          environment:
            SONAR_RUNNER_OPTS: -Xmx3062m -XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=128m

workflows:
  version: 2
  all:
    jobs:
      - build
      - analysis

