---
swagger: '2.0'
info:
  version: 1.0.0
  title: Firefly
  description: |

consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
host: localhost:8080
basePath: /api/v1
paths:
  /tasks:
    get:
      summary: List all tasks
      responses:
        200:
          description: Array of tasks.
          examples:
            application/json: >
              [
                {
                  "date": "01/01/2001",
                  "description": "Description of first task",
                  "id": 0,
                  "module": 0,
                  "name": "Title of first task",
                  "state": 3,
                  "type": 1,
                  "user_name": "toto"
                },
                {
                  "date": "01/01/2001",
                  "description": "Description of second task",
                  "id": 1,
                  "module": 0,
                  "name": "Title of second task",
                  "state": 3,
                  "type": 1,
                  "user_name": "toto"
                }
              ]
          schema:
            type: array
            items:
              $ref: '#/definitions/FullTask'
    post:
      summary: Create a task
      responses:
        200:
          description: Task created with success.
          examples:
            application/json: >
              {
                "date": "01/01/2001",
                "description": "Description of third task",
                "id": 2,
                "module": 0,
                "name": "Title of third task",
                "state": 0,
                "type": 1,
                "user_name": "toto"
              }
          schema:
            $ref: '#/definitions/FullTask'
      parameters:
        - name: name
          in: body
          type: string
          description: Name of the task
          required: true
        - name: description
          in: body
          type: string
          description: Description of the task
          required: true
        - name: user
          in: body
          type: string
          description: User login who creates the task
          required: true
        - name: module
          in: body
          type: int
          description: Module id
          required: true
        - name: type
          in: body
          type: int
          description: Type id
          required: true

  /tasks/{id}:
    get:
      summary: Get a task by id
      responses:
        200:
          description: The task of the given id.
          examples:
            application/json: >
              {
                "date": "01/01/2001",
                "description": "Description of third task",
                "id": 2,
                "module": 0,
                "name": "Title of third task",
                "state": 0,
                "type": 1,
                "user_name": "toto"
              }
      parameters:
        - name: id
          in: path
          description: Task ID
          type: integer
          required: true
  /tasks/{id}/run:
    post:
      summary: Run a task by id
      responses:
        200:
          description: A simple result ok json.
          examples:
            application/json: >
              {
                "resultOk": true
              }
      parameters:
        - name: id
          in: path
          description: Task ID
          type: integer
          required: true
  /tasks/{id}/progress/{progress}:
    get:
      summary: WIP on this endpoint
      responses:
        200:
          description: Get the progress of a task from last progress id.
          schema:
            type: object
            properties:
              new_progress:
                type: integer
                example: 1
                description: The last progress ID that should be used for next progress request.
              operations:
                type: array
                items:
                  $ref: '#/definitions/Operation'
        410:
          description: The task is not running anymore so operations are gone. Now use the result endpoint.
      parameters:
        - name: id
          in: path
          description: Task ID
          type: integer
          required: true
        - name: progress
          in: path
          description: Current progress ID of the task (defaulted to 0)
          type: integer
          required: true
          default: 0
  /tasks/{id}/result:
    get:
      summary: WIP on this endpoint
      responses:
        200:
          description: Get the final result of a task.
        404:
          description: There is no result for this task because it is probably running.
      parameters:
        - name: id
          in: path
          description: Task ID
          type: integer
          required: true
definitions:
  Task:
    required:
      - name
      - description
      - type
      - module
    properties:
      name:
        type: string
        description: Display name of the task.
      description:
        type: string
        description: Description of the task.
      type:
        type: integer
        description: The unique ID which identify the type of the task.
      module:
        type: integer
        description: The unique ID which identify the module to which the task belongs.
  FullTask:
    allOf:
      - $ref: '#/definitions/Task'
      - properties:
          id:
            type: integer
            description: Unique id representing a specific task.
          state:
            type: integer
            description: State of the task.
            default: started
            enum:
              - started
              - stopped
          user_name:
            type: string
            description: Name of the user who created the task.
          date:
            type: string
            description: Date and time of the task creation, in iso format.
  Operation:
    type: object
    properties:
      id:
        type: integer
        description: Unique ID of the operation
      type:
        type: string
        enum:
          - "ADD"
          - "REMOVE"
        description: Type of operation that should be done.
      json:
        type: string
        description: JSON field defining the object that should be processed. <br>Properties of json field are not decided for the moment...

